Controllers/ListEmployeeController.cs
using ArtsofteTestProject.Models;
using ArtsofteTestProject.Services;
using ArtsofteTestProject.ViewModels;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace ArtsofteTestProject.Controllers
{
    public class ListEmployeeController : Controller
    {
        private readonly IEmployeeData _employeeData;

        public ListEmployeeController(IEmployeeData employeeData)
        {
            _employeeData = employeeData;
        }

        public IActionResult Index()
        {
            var model = new ListEmployeePageViewModel
            {
                EmployeePlaces = _employeeData.GetAllEmployeePlaces()
            };
            return View(model);
        }

        public IActionResult DeleteEmployeePlace()
        {
            var form = HttpContext.Request.Form;
            var idForRemove = form.Keys.FirstOrDefault();

            try
            {
                var employeePlace = _employeeData.GetEmployeePlace(new Guid(idForRemove));

                _employeeData.DeleteEmployeePlace(employeePlace);
            }
            catch (Exception e)
            {
                //return FormResult.CreateErrorResult($"Problem with remove: {e.Message}");
            }

            return Content("test");
        }

        public JsonResult AutocompleteSearch(string term)
        {
            var names = _employeeData.GetAllEmployee()
                .Where( a => a.Name.Contains(term))
                 .Select(a => new { value = a.Name })
                            .Distinct();

            return Json(names);
        }

        [Route("add")]
        [HttpGet]
        public IActionResult Add()
        {
            ViewBag.departmentList = _employeeData.GetAllDepartments();
            ViewBag.programmingLanguageList = _employeeData.GetAllProgrammingLanguages();
            return View();
        }

        [Route("add")]
        [HttpPost]
        public IActionResult Add(AddEmployeePageViewModel model)
        {
            var form = Request.Form;
            string departmentId = form["Department"]!;
            string programmingLanguageId = form["ProgrammingLanguage"]!;

            var employee = new Employee
            {
                Id = Guid.NewGuid(),
                Name = model.Employee.Name,
                Surname = model.Employee.Surname,
                Age = model.Employee.Age,
                Gender = model.Employee.Gender
            };
            _employeeData.AddEmployee(employee);

            var employeePlace = new EmployeePlace
            {
                Id = Guid.NewGuid(),
                EmployeeId = employee.Id,
                DepartmentId = new Guid(departmentId),
                ProgrammingLanguageId = new Guid(programmingLanguageId)
            };
            _employeeData.AddEmployeePlace(employeePlace);

            return RedirectToAction("Index");
        }

        [Route("edit")]
        [HttpGet]
        public IActionResult Edit(Guid? id)
        {
            if (id != null)
            {
                var model = new EditEmployeePageViewModel
                {
                    EmployeePlace = _employeeData.GetEmployeePlace(id)
                };
                model.Employee = _employeeData.GetEmployee(model.EmployeePlace.EmployeeId);
                model.Departments = _employeeData.GetAllDepartments();
                model.ProgrammingLanguages = _employeeData.GetAllProgrammingLanguages();

                if (model == null)
                {
                    return NotFound($"Employee place with id = {id} not found");
                }

                return View(model);
            }
            return NotFound();
        }

        [Route("edit")]
        [HttpPost]
        public IActionResult Edit(EditEmployeePageViewModel model)
        {
            var employee = _employeeData.GetEmployee(model.Employee.Id);
            employee.Name = model.Employee.Name;
            employee.Surname = model.Employee.Surname;
            employee.Age = model.Employee.Age;
            employee.Gender = model.Employee.Gender;
            _employeeData.EditEmployee(employee);

            var employeePlace = _employeeData.GetEmployeePlace(model.EmployeePlace.Id);
            employeePlace.EmployeeId = employee.Id;
            employeePlace.DepartmentId = model.EmployeePlace.DepartmentId;
            employeePlace.ProgrammingLanguageId = model.EmployeePlace.ProgrammingLanguageId;
            _employeeData.EditEmployeePlace(employeePlace);

            return RedirectToAction("Index");
        }


            [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }

        [Route("department")]
        [HttpGet]
        public IActionResult AddDepartment()
        {
            return View();
        }

        [Route("department")]
        [HttpPost]
        public IActionResult AddDepartment(AddEmployeePageViewModel model)
        {
            var department = new Department
            {
                Id = Guid.NewGuid(),
                Name = model.Department.Name,
                Floor = model.Department.Floor
            };
            _employeeData.AddDepartment(department);

            return RedirectToAction("Index");
        }

        [Route("language")]
        [HttpGet]
        public IActionResult AddLanguage()
        {
            return View();
        }

        [Route("language")]
        [HttpPost]
        public IActionResult AddLanguage(AddEmployeePageViewModel model)
        {
            var language = new ProgrammingLanguage
            {
                Id = Guid.NewGuid(),
                Name = model.ProgrammingLanguage.Name,
            };
            _employeeData.AddProgrammingLanguage(language);

            return RedirectToAction("Index");
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ArtsofteTestProject</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/lib/jqueryui/themes/base/jquery-ui.min.css" />
    <link rel="stylesheet" href="~/lib/jqueryui/themes/base/theme.min.css"/>
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ArtsofteTestProject.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="ListEmployee" asp-action="Index">ArtsofteTestProject</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="ListEmployee" asp-action="Index">Home</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - ArtsofteTestProject
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/jqueryui/jquery-ui.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>